### ISSUE TITLE
Can we refer to examples in an obsoleted RFC? (section 2.2.1)

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/groupcomm-bis#12]
Can we refer to examples in an obsoleted RFC? (section 2.2.1 mentions the RFC 7390 examples)

**Comment by cabo** [comment]
What is the purpose of referring to those?
If they are illustrating normative concepts, I'd pull them over.
If they are just "look, this is one way this has been done", such a reference is OK IMHO.

**Comment by EskoDijk** [comment]
The purpose is just to point to some examples (that we didn't want to repeat), nothing normative. So it should be ok to do so.

**Comment by cabo** [comment]
You could emphasize this by using past tense (... RFC 7390 showed examples...)
