### ISSUE TITLE
Move intro text of Section 5 into an own Section 5.1?

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/groupcomm-bis#15]
The intro text of Section 5 has become quite long - it could have its own section 5.1.
This is just a nice-to-have to make text easier to refer to. (Some standards bodies use this convention. E.g. if I refer to "Section 5" currently it is not clear whether I mean the intro text or the whole of Section 5 including subsections.)
Other sections already conform to this convention. (Except section 1. Introduction ; but for an intro section it is less common to apply this convention.)

**Comment by EskoDijk** [comment]
Same pattern can be applied to the text of 6.2 -> 6.2.1

**Comment by marco-tiloca-sics** [comment]
As per the commit https://github.com/core-wg/groupcomm-bis/commit/8f776df34080199a249cf3abd579f9fc123d5385 , done for Section 5 -> 5.1.

Instead, the introductory text in Section 6.2 seems already pretty short and self-contained to be further broken down.
