### ISSUE TITLE
Do we need to mention size-based packet filtering in 6.5 6LoWPAN security considerations?

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/groupcomm-bis#16]
Idea: an ingress MPL Forwarder or 6LBR may filter ingress multicast packets based on size. E.g., any packet that would lead to (excessive) 6LoWPAN fragmentation could be dropped as a policy. Or deprioritized just like we state for MPL Forwarders / 6LR Routers.
Is this something we ought to mention in the security considerations?

**Comment by marco-tiloca-sics** [comment]
I think it's good to add.
