### ISSUE TITLE
Expand text on amplification attacks and countering

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/groupcomm-bis#22]
Based on John's review ([link](https://mailarchive.ietf.org/arch/msg/core/Z9wxTL3-hAEDT_P8JOQztTfxlVU/)), expand a bit on the following text from RFC 7252:

 "This specification attempts to reduce the
   amplification effects of multicast requests by limiting when a
   response is returned.  To limit the possibility of malicious use,
   CoAP servers SHOULD NOT accept multicast requests that can not be
   authenticated in some way, cryptographically or by some multicast
   boundary limiting the potential sources.  If possible, a CoAP server
   SHOULD limit the support for multicast requests to the specific
   resources where the feature is required."

A specific section 6.x on amplification attacks in general could be added, even. (To cross-check with what 6.2.3 writes about amplification attacks.)

**Comment by marco-tiloca-sics** [comment]
The commit https://github.com/core-wg/groupcomm-bis/commit/3eac21fbf6eb0dbf441c1e3b954a5ad6e94ee25a   adds:

- New text in Sections 4, 6.1, 6.2.3 (second bullet point)
- New Section 6.3

**Comment by marco-tiloca-sics** [comment]
The commit https://github.com/core-wg/groupcomm-bis/commit/99011a4c4b3baa4aab410c30bf52fe52db9159bb  revises the sections mentioned in the previous comment, mostly based on version -01 of [1] and the related slide  9 at [2].

[1] https://datatracker.ietf.org/doc/draft-mattsson-core-coap-attacks/
[2] https://datatracker.ietf.org/meeting/111/materials/slides-111-core-coap-attacks-00
