### ISSUE TITLE
Consider to replace terms 'backward security' and 'forward security'

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/groupcomm-bis#24]
Consider to replace terms 'backward security' and 'forward security': from what I have seen, only 'backward secrecy' and 'forward secrecy' is used instead of the terms in the current text. Correct me if I'm wrong :)

**Comment by marco-tiloca-sics** [comment]
Both versions are found in the literature about secure group communication.

An advantage of using " *-security " is to avoid confusion with "forward secrecy", which is also used in other contexts with a different meaning, more related to key agreement protocols and assurances on established session keys.

Probably it's still fine to do the change, if we phrase it as "... backward secrecy in the group".

**Comment by marco-tiloca-sics** [comment]
As per discussions at IETF 111:

* The commit https://github.com/core-wg/groupcomm-bis/commit/0a2f59858b3bdcfb6a21dda68f128bda1bc34042  presents backward/forward security more clearly as properties.
* Given the clarification above, both terms "security" and "secrecy" are fine, as long as their meaning is clear. As commented above, "security" might raise less confusion than "secrecy".
