### ISSUE TITLE
one-to-many vs. figure 1

### ISSUE THREAD

**Issue by chrysn** [core-wg/groupcomm-bis#27]
There seems to be a contradiction between "There can be a one-to-one or a one-to-many relation between security groups and CoAP groups" and figure 1 that has a 1..n / 1..n relation between CoAP groups and security groups. The figure (which I think is correct here) would imply that the sentence should rather say "can be a many-to-many relation between ... (but often it is one-to-one)".

**Comment by marco-tiloca-sics** [comment]
You are right, and the same applied also to the following sentence about the relation between security groups and application groups.
